[package]
name = "nv-telemetry-redfish"
description = "Redfish acquisition for nv-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nv-telemetry-model.workspace = true
nv-telemetry-source.workspace = true

[lints]
workspace = true
