// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! The contract lock: a checked-in, deterministic record of every declaration
//! in the contract package.
//!
//! Regenerating it and finding the working tree unchanged is what makes
//! `--check` able to fail, so a schema edit without a regenerated tree cannot
//! reach CI. It stands in for the generated Rust until there is any, and
//! remains useful afterwards as a readable record of the contract.
//!
//! Backward compatibility is not judged here. `buf breaking` owns that, and
//! covers reserved ranges, enum changes, JSON names, and oneof moves that a
//! comparison written here would have to grow one case at a time.
//!
//! The format is one sorted line per declaration so that a review reads it as
//! a schema-shaped diff. Staleness is a byte comparison against the committed
//! file, so nothing reads it back: a change to the header is as much a reason
//! to regenerate as a change to a field.

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fmt::Write as _;

use prost_reflect::DescriptorPool;
use prost_reflect::FieldDescriptor;
use prost_reflect::Kind;

use crate::is_contract_package;
use crate::options::Vocabulary;

const HEADER: &str = "\
# nv-telemetry contract lock.
#
# Generated by `make codegen`; do not edit. One line per declaration, sorted,
# so that a schema change reads as a diff. `make check-codegen` fails if this
# file disagrees with the schema. Backward compatibility is checked separately,
# by `make proto-breaking`.
";

/// One field as the lock records it.
///
/// Annotations are recorded alongside the shape because they are what decides
/// whether a zero can be fabricated. A lock that tracked only numbers and
/// types would let `finite` or `zero_is_meaningful` be added or removed with
/// no diff at all, which is most of what the lock is for.
#[derive(Clone, Debug, PartialEq, Eq)]
struct Entry {
    name: String,
    kind: String,
    cardinality: String,
    presence: String,
    annotations: String,
}

/// Every declaration in the contract, keyed by message and field number.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Snapshot {
    fields: BTreeMap<(String, u32), Entry>,
    messages: BTreeSet<String>,
}

impl Snapshot {
    /// Records every contract declaration in `pool`.
    pub fn capture(pool: &DescriptorPool, vocabulary: &Vocabulary) -> Self {
        let mut snapshot = Self::default();

        for message in pool.all_messages() {
            if !is_contract_package(message.package_name()) || message.is_map_entry() {
                continue;
            }
            let annotations =
                vocabulary
                    .message_invariant(&message)
                    .map_or_else(String::new, |invariant| {
                        let mut parts = Vec::new();
                        if invariant.validated {
                            parts.push("validated".to_owned());
                        }
                        if invariant.hashable {
                            parts.push("hashable".to_owned());
                        }
                        if let Some(depth) = invariant.max_depth {
                            parts.push(format!("max_depth={depth}"));
                        }
                        parts.join(" ")
                    });
            snapshot.messages.insert(
                format!("{} {annotations}", message.full_name())
                    .trim_end()
                    .to_owned(),
            );

            for field in message.fields() {
                snapshot.fields.insert(
                    (message.full_name().to_owned(), field.number()),
                    Entry {
                        name: field.name().to_owned(),
                        kind: kind_name(&field),
                        annotations: field_annotations(vocabulary, &field),
                        cardinality: if field.is_map() {
                            "map"
                        } else if field.is_list() {
                            "repeated"
                        } else {
                            "single"
                        }
                        .to_owned(),
                        presence: if field.supports_presence() {
                            "explicit"
                        } else {
                            "implicit"
                        }
                        .to_owned(),
                    },
                );
            }
        }

        snapshot
    }

    /// Renders the lock file.
    pub fn render(&self) -> String {
        let mut out = String::from(HEADER);
        for name in &self.messages {
            let _ = writeln!(out, "message {name}");
        }
        for ((message, number), entry) in &self.fields {
            let _ = writeln!(
                out,
                "{}",
                format!(
                    "field {message} {number} {} {} {} {} {}",
                    entry.name, entry.kind, entry.cardinality, entry.presence, entry.annotations
                )
                .trim_end()
            );
        }
        out
    }
}

/// Renders a field's type.
///
/// A map is rendered as its key and value types rather than as the synthetic
/// entry message, whose name is derived from the field name and so hides both.
/// Changing a map's key type from `string` to `int64` is wire-breaking and
/// would otherwise leave the lock unchanged.
fn kind_name(field: &FieldDescriptor) -> String {
    if field.is_map() {
        if let Kind::Message(entry) = field.kind() {
            return format!(
                "map<{},{}>",
                type_name(&entry.map_entry_key_field().kind()),
                type_name(&entry.map_entry_value_field().kind())
            );
        }
    }
    type_name(&field.kind())
}

fn type_name(kind: &Kind) -> String {
    match kind {
        Kind::Message(message) => message.full_name().to_owned(),
        Kind::Enum(enumeration) => enumeration.full_name().to_owned(),
        other => format!("{other:?}").to_lowercase(),
    }
}

fn field_annotations(vocabulary: &Vocabulary, field: &FieldDescriptor) -> String {
    let Some(invariant) = vocabulary.field_invariant(field) else {
        return String::new();
    };
    let mut parts = Vec::new();
    if invariant.zero_is_meaningful {
        parts.push("zero_is_meaningful".to_owned());
    }
    if invariant.finite {
        parts.push("finite".to_owned());
    }
    if invariant.required {
        parts.push("required".to_owned());
    }
    if invariant.unordered {
        parts.push("unordered".to_owned());
    }
    if let Some(items) = invariant.max_items {
        parts.push(format!("max_items={items}"));
    }
    if let Some(len) = invariant.max_len {
        parts.push(format!("max_len={len}"));
    }
    parts.join(" ")
}
