// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Mechanical Rust rendering for checked projection plans.
//!
//! `compile` owns schema resolution, conversion selection, identity, target
//! assembly, gates, and names. This module only turns those typed facts into
//! tokens, parses the complete file, and pretty-prints it.

use std::fmt::Write as _;
use std::path::PathBuf;

use nv_redfish_csdl_compiler::generator::casemungler;
use proc_macro2::Ident;
use proc_macro2::TokenStream;
use quote::format_ident;
use quote::quote;

use crate::projection::compile::AssemblyPlan;
use crate::projection::compile::BackendPlan;
use crate::projection::compile::CompiledManifests;
use crate::projection::compile::ConversionPlan;
use crate::projection::compile::GatePlan;
use crate::projection::compile::GroupBuildPlan;
use crate::projection::compile::IdentityKind;
use crate::projection::compile::InstancePlan;
use crate::projection::compile::ManifestPlan;
use crate::projection::compile::NullPlan;
use crate::projection::compile::OutputPlan;
use crate::projection::compile::ReadPlan;
use crate::projection::compile::SourcePlan;
use crate::projection::compile::SubjectScopePlan;
use crate::projection::compile::TextCheck;
use crate::projection::compile::TextDestination;
use crate::projection::location::LocationPattern;
use crate::projection::location::LocationSegment;
use crate::projection::Shape;
use crate::projection::Step;
use crate::provenance;
use crate::wrapper::names::ident;
use crate::wrapper::names::short_name;

const HEADER: &str = "\
// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
";

/// Renders every generated projection file, keyed by workspace-relative
/// path: one module per manifest, plus the module root and provenance table
/// per source crate.
///
/// # Errors
///
/// Only if a renderer template assembles invalid Rust. Manifest limitations
/// have already become compile violations before this function can be called.
pub fn emit(compiled: &CompiledManifests) -> Result<Vec<(PathBuf, String)>, String> {
    let mut files = Vec::new();
    for crate_plan in &compiled.crates {
        let generated = PathBuf::from("sources")
            .join(&crate_plan.crate_source)
            .join("src")
            .join("generated");
        let mut modules = Vec::new();
        for manifest in &crate_plan.manifests {
            files.push((
                generated.join(format!("{}.rs", manifest.module)),
                render_manifest(manifest)?,
            ));
            modules.push(manifest.module.clone());
        }
        files.push((
            generated.join("provenance.rs"),
            provenance::render(&crate_plan.provenance),
        ));
        files.push((generated.join("mod.rs"), module_root(&modules)));
    }
    Ok(files)
}

fn render_manifest(manifest: &ManifestPlan) -> Result<String, String> {
    let mut items = TokenStream::new();
    for source in &manifest.sources {
        items.extend(source_type_items(manifest, source));
    }
    let parsed = syn::parse2::<syn::File>(items).map_err(|error| {
        format!(
            "{}: the projection emitter produced invalid Rust: {error}; this is a codegen template bug",
            manifest.relative_path
        )
    })?;
    let body = prettyplease::unparse(&parsed);

    let mut header = String::from(HEADER);
    let _ = write!(
        header,
        "\n//! Generated from `{}` by `make codegen`. Do not edit.\n\
         //!\n\
         //! Deterministic, I/O-free projection from decoded source types to\n\
         //! validated observation parts plus issues. Every field is evaluated\n\
         //! before identity is decided, absence produces no output, and an\n\
         //! unusable answer produces an issue beside the parts.\n\n\
         // Generated code holds the line on correctness lints; the pedantic\n\
         // group is style advice for humans and is exactly where a clippy\n\
         // release breaks a checked-in file that no one edited.\n\
         #![allow(clippy::pedantic)]\n",
        manifest.relative_path,
    );
    Ok(format!("{header}\n{body}"))
}

/// The generated module root: written rather than hand-maintained so the
/// whole directory is generated output and the staleness gate covers it.
fn module_root(modules: &[String]) -> String {
    let mut root = String::from(HEADER);
    root.push_str(
        "\n//! Generated by `make codegen` from the manifests under `manifests/`.\n\
         //! Do not edit by hand.\n\n\
         // Formatted by the generator and byte-compared against it. rustfmt.toml\n\
         // excludes generated trees, but `ignore` is nightly-only: stable rustfmt\n\
         // would reformat and the staleness gate would then report a schema\n\
         // problem that does not exist.\n",
    );
    for module in modules {
        let _ = write!(root, "#[rustfmt::skip]\npub(crate) mod {module};\n\n");
    }
    root.push_str("#[rustfmt::skip]\npub(crate) mod provenance;\n");
    root
}

#[allow(clippy::too_many_lines)]
fn source_type_items(manifest: &ManifestPlan, source: &SourcePlan) -> TokenStream {
    let parts_name = ident(&source.parts_name);
    let fn_name = ident(&source.function_name);
    let source_param = ident(&source.source_param);
    let parts_fields = source.collections.iter().map(|collection| {
        let field = ident(&collection.field);
        let ty = ident(&collection.model_type);
        quote! {
            pub(crate) #field: Vec<::nv_telemetry_model::#ty>,
        }
    });
    let parts_idents = source
        .collections
        .iter()
        .map(|collection| ident(&collection.field))
        .collect::<Vec<_>>();

    let mut evaluations = TokenStream::new();
    let mut assemblies = TokenStream::new();
    for instance in &source.instances {
        for evaluation in &instance.evaluations {
            let local = ident(&evaluation.local);
            let conversion = conversion(
                manifest.backend,
                &evaluation.conversion,
                &evaluation.read.issue_path,
            );
            let value = leaf_match(&source_param, &evaluation.read, &conversion);
            evaluations.extend(quote! { let #local = #value; });
        }
        for group in &instance.groups {
            evaluations.extend(group_evaluation(group));
        }
        for assembly in &instance.assemblies {
            evaluations.extend(assembly_evaluation(
                manifest.backend,
                &source_param,
                assembly,
            ));
        }
        assemblies.extend(instance_assembly(instance));
    }

    let (subject_tokens, helpers) = subject_derivation(manifest.backend, source);
    let key_binding = source.needs_key.then(|| {
        quote! {
            let key = ::nv_telemetry_model::SignalKey::builder()
                .subject(subject.clone())
                .build()?;
        }
    });
    let location_param = if source.subject.needs_location {
        ident("location")
    } else {
        ident("_location")
    };
    let source_ty = source_type_tokens(
        manifest.backend,
        &source.source_namespace,
        &source.source_type,
    );
    let source_type = &source.source_type;

    let parts_doc = docs(&format!(
        "What one `{source_type}` document projected to. The provider\n\
         assembles batches from these; identity failure leaves every\n\
         collection empty while the issues still name each fault."
    ));
    let fn_doc = docs(&format!(
        "Projects one `{source_type}` document, located at the *requested*\n\
         URI.\n\
         \n\
         # Errors\n\
         \n\
         `Err` is the residual tier only — a builder refusing inputs this\n\
         function already triaged is a projection bug, and a bug is an\n\
         operational fact for the status stream rather than device data.\n\
         Everything a device can cause comes back as issues inside the\n\
         parts."
    ));

    quote! {
        #parts_doc
        #[derive(Debug)]
        pub(crate) struct #parts_name {
            #(#parts_fields)*
            /// The source fields that projected to nothing, and why.
            pub(crate) issues: Vec<::nv_telemetry_source::ProjectionIssue>,
        }

        #fn_doc
        pub(crate) fn #fn_name(
            #source_param: &#source_ty,
            #location_param: &str,
        ) -> Result<#parts_name, ::nv_telemetry_model::Invalid> {
            let mut issues = Vec::new();

            #evaluations

            #subject_tokens
            let Some(subject) = subject else {
                return Ok(#parts_name {
                    #(#parts_idents: Vec::new(),)*
                    issues,
                });
            };

            #key_binding
            #(let mut #parts_idents = Vec::new();)*

            #assemblies

            Ok(#parts_name {
                #(#parts_idents,)*
                issues,
            })
        }

        #helpers
    }
}

fn group_evaluation(group: &GroupBuildPlan) -> TokenStream {
    let local = ident(&group.local);
    let model_type = ident(&group.model_type);
    let member_locals = group
        .members
        .iter()
        .map(|member| ident(&member.local))
        .collect::<Vec<_>>();
    let setters = group
        .members
        .iter()
        .map(|member| ident(&member.setter))
        .collect::<Vec<_>>();
    let blame = group_blame_chain(&group.members, &group.issue_path);
    let gate = group.gate.as_ref().map(|gate| {
        let local = ident(&gate.local);
        let conditions = gate.conditions.iter().map(gate_tokens);
        quote! { let #local = #(#conditions)&&*; }
    });
    quote! {
        #gate
        let #local = if #(#member_locals.is_some())||* {
            let mut builder = ::nv_telemetry_model::#model_type::builder();
            #(if let Some(value) = #member_locals {
                builder = builder.#setters(value);
            })*
            match builder.build() {
                Ok(value) => Some(value),
                Err(error) => {
                    let path = #blame;
                    issues.push(::nv_telemetry_source::ProjectionIssue::invalid(
                        path,
                        error.to_string(),
                    ));
                    None
                }
            }
        } else {
            None
        };
    }
}

fn assembly_evaluation(
    backend: BackendPlan,
    source_param: &Ident,
    assembly: &AssemblyPlan,
) -> TokenStream {
    let local = ident(&assembly.local);
    let entries = assembly.entries.iter().map(|entry| {
        let conversion = conversion(backend, &entry.conversion, &entry.read.issue_path);
        let evaluation = leaf_match(source_param, &entry.read, &conversion);
        let key = &entry.key;
        quote! {
            if let Some(value) = #evaluation {
                #local.push((#key.to_owned(), value));
            }
        }
    });
    quote! {
        let mut #local: Vec<(String, ::nv_telemetry_model::Value)> = Vec::new();
        #(#entries)*
    }
}

fn conversion(backend: BackendPlan, plan: &ConversionPlan, issue_path: &str) -> TokenStream {
    match plan {
        ConversionPlan::DecimalValue { constructor } => {
            let constructor = vocab_type(constructor);
            quote! {
                match #constructor::double(value) {
                    Ok(value) => Some(value),
                    Err(error) => {
                        issues.push(::nv_telemetry_source::ProjectionIssue::invalid(
                            #issue_path,
                            error.to_string(),
                        ));
                        None
                    }
                }
            }
        }
        ConversionPlan::Text { check, destination } => {
            let value = quote! { value };
            let accept = text_accept(destination, &value);
            checked_text(check, issue_path, accept)
        }
        ConversionPlan::Enum {
            namespace,
            name,
            rows,
            destination,
        } => {
            let enum_type = source_type_tokens(backend, namespace, name);
            let arms = rows.iter().map(|(from, to)| {
                let variant = escaped_ident(&casemungler::to_camel(from));
                let value = quote! { #to };
                let output = text_accept(destination, &value);
                quote! { #enum_type::#variant => #output, }
            });
            quote! {
                match value {
                    #(#arms)*
                    _ => {
                        issues.push(::nv_telemetry_source::ProjectionIssue::invalid(
                            #issue_path,
                            "outside the known value set",
                        ));
                        None
                    }
                }
            }
        }
    }
}

fn text_accept(destination: &TextDestination, value: &TokenStream) -> TokenStream {
    match destination {
        TextDestination::Plain => quote! { Some(#value) },
        TextDestination::Vocabulary(vocabulary) => {
            let constructor = vocab_type(vocabulary);
            quote! { Some(#constructor::string(#value)?) }
        }
    }
}

fn checked_text(check: &TextCheck, issue_path: &str, accept: TokenStream) -> TokenStream {
    let mut arms = TokenStream::new();
    if check.non_empty {
        let detail = format!("`{}`: present but empty", check.field_name);
        arms.extend(quote! {
            if value.is_empty() {
                issues.push(::nv_telemetry_source::ProjectionIssue::invalid(
                    #issue_path,
                    #detail,
                ));
                None
            } else
        });
    }
    if let Some(constant) = &check.max_len_constant {
        let constant = ident(constant);
        let detail = format!(
            "`{}`: {{}} bytes long, over the schema's bound of {{}}",
            check.field_name
        );
        arms.extend(quote! {
            if value.len() > ::nv_telemetry_model::limits::#constant as usize {
                issues.push(::nv_telemetry_source::ProjectionIssue::invalid(
                    #issue_path,
                    format!(#detail, value.len(), ::nv_telemetry_model::limits::#constant),
                ));
                None
            } else
        });
    }
    if arms.is_empty() {
        accept
    } else {
        quote! { #arms { #accept } }
    }
}

fn instance_assembly(instance: &InstancePlan) -> TokenStream {
    let target = ident(&instance.target_model);
    let collection = ident(&instance.collection);
    let identity_setter = ident(instance.profile.identity_field);
    let identity = match instance.profile.identity {
        IdentityKind::SignalKey => quote! { builder = builder.#identity_setter(key.clone()); },
        IdentityKind::Subject => {
            quote! { builder = builder.#identity_setter(subject.clone()); }
        }
    };
    let outputs = instance.outputs.iter().map(|output| {
        let local = ident(&output.local);
        let setter = ident(&output.setter);
        quote! {
            if let Some(value) = #local {
                builder = builder.#setter(value);
            }
        }
    });
    let constants = instance.constants.iter().map(|constant| {
        let setter = ident(&constant.setter);
        let value = &constant.value;
        let value = match &constant.destination {
            TextDestination::Plain => quote! { #value },
            TextDestination::Vocabulary(vocabulary) => {
                let constructor = vocab_type(vocabulary);
                quote! { #constructor::string(#value)? }
            }
        };
        quote! { builder = builder.#setter(#value); }
    });
    let assemblies = instance.assemblies.iter().map(|assembly| {
        let setter = ident(&assembly.setter);
        let local = ident(&assembly.local);
        quote! {
            builder = builder.#setter(::nv_telemetry_model::Value::map(#local)?);
        }
    });
    let body = quote! {
        let mut builder = ::nv_telemetry_model::#target::builder();
        #identity
        #(#outputs)*
        #(#constants)*
        #(#assemblies)*
        #collection.push(builder.build()?);
    };
    let conditions = instance
        .outputs
        .iter()
        .flat_map(|output| output.gates.iter().map(gate_tokens))
        .chain(instance.assemblies.iter().map(|assembly| {
            let local = ident(&assembly.local);
            quote! { !#local.is_empty() }
        }))
        .collect::<Vec<_>>();
    if conditions.is_empty() {
        body
    } else {
        quote! {
            if #(#conditions)&&* {
                #body
            }
        }
    }
}

fn gate_tokens(gate: &GatePlan) -> TokenStream {
    match gate {
        GatePlan::Present(local) => {
            let local = ident(local);
            quote! { #local.is_some() }
        }
        GatePlan::Flag(local) => {
            let local = ident(local);
            quote! { #local }
        }
    }
}

#[allow(clippy::too_many_lines)]
fn subject_derivation(backend: BackendPlan, source: &SourcePlan) -> (TokenStream, TokenStream) {
    let source_param = ident(&source.source_param);
    let id_local = ident(&source.subject.id.local);
    let id_leaf = source
        .subject
        .id
        .steps
        .last()
        .expect("a subject id plan has a leaf");
    let id_place = place(id_leaf.hops, &source_field_ident(&id_leaf.property));
    let id_blame = &source.subject.id.issue_path;
    let id_conversion = checked_text(&source.subject.id.check, id_blame, quote! { Some(value) });
    let mut evaluations = quote! {
        let #id_local = {
            let value = #source_param #id_place.clone();
            #id_conversion
        };
    };

    let mut helpers = TokenStream::new();
    let mut scope_locals = Vec::new();
    let mut blames = Vec::new();
    for scope in &source.subject.scopes {
        match scope {
            SubjectScopePlan::Payload { local, read, check } => {
                let local = ident(local);
                let conversion = checked_text(check, &read.issue_path, quote! { Some(value) });
                let evaluation = leaf_match(&source_param, read, &conversion);
                evaluations.extend(quote! { let #local = #evaluation; });
                scope_locals.push(local);
                blames.push(read.issue_path.clone());
            }
            SubjectScopePlan::Location {
                local,
                helper,
                pattern,
                check,
            } => {
                let local = ident(local);
                let helper = ident(helper);
                helpers.extend(location_helper(backend, &helper, pattern));
                let capture = pattern.capture();
                // A requested URI is untrusted and may carry query secrets.
                // The issue identifies the `uri` field already; keep detail
                // static rather than copying the request into diagnostics.
                let detail = format!("requested location has no {capture} segment");
                let conversion = checked_text(check, "uri", quote! { Some(value) });
                evaluations.extend(quote! {
                    let #local = match #helper(location) {
                        Some(value) => #conversion,
                        None => {
                            issues.push(::nv_telemetry_source::ProjectionIssue::invalid(
                                "uri",
                                #detail,
                            ));
                            None
                        }
                    };
                });
                scope_locals.push(local);
                blames.push("uri".to_owned());
            }
        }
    }

    let kind = &source.subject.kind;
    let scope_blame = blame_chain(&blames, id_blame);
    let derivation = quote! {
        match (#id_local, #(#scope_locals,)*) {
            (Some(#id_local), #(Some(#scope_locals),)*) => {
                match ::nv_telemetry_model::Subject::builder()
                    .kind(#kind)
                    .scope(vec![#(#scope_locals.to_owned()),*])
                    .id(#id_local)
                    .build()
                {
                    Ok(subject) => Some(subject),
                    Err(error) => {
                        let path = if error.path().starts_with("id") {
                            #id_blame
                        } else {
                            #scope_blame
                        };
                        issues.push(::nv_telemetry_source::ProjectionIssue::invalid(
                            path,
                            error.to_string(),
                        ));
                        None
                    }
                }
            }
            _ => None,
        }
    };
    (
        quote! {
            #evaluations
            let subject = #derivation;
        },
        helpers,
    )
}

fn location_helper(backend: BackendPlan, name: &Ident, pattern: &LocationPattern) -> TokenStream {
    let canonical = location_grammar(backend);
    let checks = pattern.segments().iter().map(|segment| match segment {
        LocationSegment::Capture => quote! {
            let captured = segments.next().filter(|segment| !segment.is_empty())?;
        },
        LocationSegment::Wildcard => quote! {
            let _ = segments.next().filter(|segment| !segment.is_empty())?;
        },
        LocationSegment::Literal(segment) => quote! {
            if segments.next()? != #segment {
                return None;
            }
        },
    });
    let template = pattern.template();
    let capture = pattern.capture();
    let doc = docs(&format!(
        "Matches `{template}`, yielding `{{{capture}}}`: the subject's\n\
         scope comes from the requested location, never from the\n\
         payload's own claim about itself."
    ));
    quote! {
        #doc
        fn #name(location: &str) -> Option<&str> {
            let mut segments = #canonical(location).strip_prefix('/')?.split('/');
            #(#checks)*
            if segments.next().is_some() {
                return None;
            }
            Some(captured)
        }
    }
}

/// The evaluation of one leaf: source access composed with presence shape,
/// then the checked conversion over a present `value`.
fn leaf_match(source_param: &Ident, read: &ReadPlan, conversion: &TokenStream) -> TokenStream {
    let (leaf, prefix_steps) = read
        .steps
        .split_last()
        .expect("a resolved read plan has a leaf");

    // An explicit null in an intermediate field must not collapse into
    // absence, and required-nullable leaves nested below an optional parent
    // need both states too. The usual compact Option composition remains for
    // paths whose Rust shape preserves every state by itself.
    let precise_presence = prefix_steps
        .iter()
        .any(|step| matches!(step.shape(), Shape::RequiredNullable | Shape::Nullable))
        || (leaf.shape() == Shape::RequiredNullable
            && prefix_steps.iter().any(|step| step.shape() != Shape::Bare));
    if precise_presence {
        return precise_leaf_match(source_param, read, conversion);
    }
    let (leaf_expr, effective) = compact_leaf_expression(source_param, leaf, prefix_steps);

    let issue_path = &read.issue_path;
    let absent = absent_value(read);
    match effective {
        Shape::Bare => quote! {
            {
                let value = #leaf_expr;
                #conversion
            }
        },
        Shape::RequiredNullable if read.null_policy == NullPlan::Invalid => quote! {
            match #leaf_expr {
                Some(value) => #conversion,
                None => {
                    issues.push(::nv_telemetry_source::ProjectionIssue::invalid(
                        #issue_path,
                        "explicitly null",
                    ));
                    None
                }
            }
        },
        Shape::Optional | Shape::RequiredNullable => quote! {
            match #leaf_expr {
                Some(value) => #conversion,
                None => #absent,
            }
        },
        Shape::Nullable if read.null_policy == NullPlan::Invalid => quote! {
            match #leaf_expr {
                Some(Some(value)) => #conversion,
                Some(None) => {
                    issues.push(::nv_telemetry_source::ProjectionIssue::invalid(
                        #issue_path,
                        "explicitly null",
                    ));
                    None
                }
                None => #absent,
            }
        },
        Shape::Nullable => quote! {
            match #leaf_expr {
                Some(Some(value)) => #conversion,
                _ => #absent,
            }
        },
    }
}

fn compact_leaf_expression(
    source_param: &Ident,
    leaf: &Step,
    prefix_steps: &[Step],
) -> (TokenStream, Shape) {
    let mut expression = quote! { #source_param };
    let mut optional = false;
    for step in prefix_steps {
        let step_place = place(step.hops, &source_field_ident(&step.property));
        expression = match (optional, step.shape()) {
            (_, Shape::RequiredNullable | Shape::Nullable) => {
                unreachable!("handled by precise presence")
            }
            (false, Shape::Bare) => quote! { #expression #step_place },
            (false, Shape::Optional) => {
                optional = true;
                quote! { #expression #step_place.as_ref() }
            }
            (true, Shape::Bare) => quote! { #expression.map(|value| &value #step_place) },
            (true, Shape::Optional) => {
                quote! { #expression.and_then(|value| value #step_place.as_ref()) }
            }
        };
    }

    let leaf_place = place(leaf.hops, &source_field_ident(&leaf.property));
    let extract = if leaf.is_text() {
        quote! { #leaf_place.clone() }
    } else {
        quote! { #leaf_place }
    };
    match (optional, leaf.shape()) {
        (false, shape) => (quote! { #expression #extract }, shape),
        (true, Shape::Bare) => (
            quote! { #expression.map(|value| value #extract) },
            Shape::Optional,
        ),
        (true, Shape::RequiredNullable) => unreachable!("handled by precise presence"),
        (true, shape) => (
            quote! { #expression.and_then(|value| value #extract) },
            shape,
        ),
    }
}

fn absent_value(read: &ReadPlan) -> TokenStream {
    let issue_path = &read.issue_path;
    if read.required {
        quote! {
            {
                issues.push(::nv_telemetry_source::ProjectionIssue::missing(#issue_path));
                None
            }
        }
    } else {
        quote! { None }
    }
}

/// Evaluates a source path without conflating wire absence and explicit
/// null. This form is reserved for paths where ordinary `Option::and_then`
/// would erase one of those states.
fn precise_leaf_match(
    source_param: &Ident,
    read: &ReadPlan,
    conversion: &TokenStream,
) -> TokenStream {
    let state = ident("GeneratedProjectionValue");
    let expression = precise_leaf_expression(source_param, &read.steps, &state);

    let issue_path = &read.issue_path;
    let absent = absent_value(read);
    let null = if read.null_policy == NullPlan::Invalid {
        quote! {
            {
                issues.push(::nv_telemetry_source::ProjectionIssue::invalid(
                    #issue_path,
                    "explicitly null",
                ));
                None
            }
        }
    } else {
        absent.clone()
    };

    quote! {
        {
            enum #state<T> {
                Absent,
                Null,
                Present(T),
            }
            match #expression {
                #state::Present(value) => #conversion,
                #state::Null => #null,
                #state::Absent => #absent,
            }
        }
    }
}

fn precise_leaf_expression(source_param: &Ident, steps: &[Step], state: &Ident) -> TokenStream {
    let (leaf, prefix_steps) = steps.split_last().expect("a resolved read plan has a leaf");
    let mut expression = quote! { #state::Present(#source_param) };
    for step in prefix_steps {
        expression = advance_presence(&expression, &prefix_presence(step, state), state);
    }
    advance_presence(&expression, &leaf_presence(leaf, state), state)
}

fn advance_presence(expression: &TokenStream, present: &TokenStream, state: &Ident) -> TokenStream {
    quote! {
        match #expression {
            #state::Absent => #state::Absent,
            #state::Null => #state::Null,
            #state::Present(value) => #present,
        }
    }
}

fn prefix_presence(step: &Step, state: &Ident) -> TokenStream {
    let step_place = place(step.hops, &source_field_ident(&step.property));
    match step.shape() {
        Shape::Bare => quote! { #state::Present(&value #step_place) },
        Shape::Optional => quote! {
            match value #step_place.as_ref() {
                Some(value) => #state::Present(value),
                None => #state::Absent,
            }
        },
        Shape::RequiredNullable => quote! {
            match value #step_place.as_ref() {
                Some(value) => #state::Present(value),
                None => #state::Null,
            }
        },
        Shape::Nullable => quote! {
            match value #step_place.as_ref() {
                Some(inner) => match inner.as_ref() {
                    Some(value) => #state::Present(value),
                    None => #state::Null,
                },
                None => #state::Absent,
            }
        },
    }
}

fn leaf_presence(leaf: &Step, state: &Ident) -> TokenStream {
    let leaf_place = place(leaf.hops, &source_field_ident(&leaf.property));
    let extract = if leaf.is_text() {
        quote! { #leaf_place.clone() }
    } else {
        quote! { #leaf_place }
    };
    match leaf.shape() {
        Shape::Bare => quote! { #state::Present(value #extract) },
        Shape::Optional => quote! {
            match value #extract {
                Some(value) => #state::Present(value),
                None => #state::Absent,
            }
        },
        Shape::RequiredNullable => quote! {
            match value #extract {
                Some(value) => #state::Present(value),
                None => #state::Null,
            }
        },
        Shape::Nullable => quote! {
            match value #extract {
                Some(Some(value)) => #state::Present(value),
                Some(None) => #state::Null,
                None => #state::Absent,
            }
        },
    }
}

fn blame_chain(blames: &[String], fallback: &str) -> TokenStream {
    match blames {
        [] => quote! { #fallback },
        [only] => quote! { #only },
        many => {
            let arms = many.iter().enumerate().map(|(position, blame)| {
                let prefix = format!("scope[{position}]");
                quote! {
                    if error.path().starts_with(#prefix) {
                        #blame
                    } else
                }
            });
            let first = &many[0];
            quote! { #(#arms)* { #first } }
        }
    }
}

/// Maps a grouped builder's target-relative error path back to the source
/// read that populated that setter. The fallback is explicit for genuinely
/// cross-group rules whose path names no member.
fn group_blame_chain(members: &[OutputPlan], fallback: &str) -> TokenStream {
    let arms = members.iter().map(|member| {
        let setter = &member.setter;
        let blame = &member.issue_path;
        quote! {
            if error.path().starts_with(#setter) {
                #blame
            } else
        }
    });
    quote! { #(#arms)* { #fallback } }
}

fn source_type_tokens(backend: BackendPlan, namespace: &str, name: &str) -> TokenStream {
    let root = source_root(backend);
    let named = source_named_type(namespace, name);
    quote! { #root::#named }
}

fn source_named_type(namespace: &str, name: &str) -> TokenStream {
    let module = escaped_ident(&casemungler::to_snake(namespace));
    let name = escaped_ident(name);
    quote! { #module::#name }
}

fn source_root(backend: BackendPlan) -> TokenStream {
    match backend {
        BackendPlan::Redfish => quote! { ::nv_redfish::schema },
    }
}

fn location_grammar(backend: BackendPlan) -> TokenStream {
    match backend {
        BackendPlan::Redfish => quote! { crate::uri::canonical },
    }
}

fn place(hops: usize, field: &Ident) -> TokenStream {
    let bases = std::iter::repeat_n(quote! { .base }, hops).collect::<TokenStream>();
    quote! { #bases.#field }
}

fn source_field_ident(property: &str) -> Ident {
    escaped_ident(&casemungler::to_snake(property))
}

fn vocab_type(full_name: &str) -> TokenStream {
    let short = ident(&short_name(full_name));
    quote! { ::nv_telemetry_model::#short }
}

fn docs(text: &str) -> TokenStream {
    crate::wrapper::names::docs(&text.split('\n').map(str::trim_end).collect::<Vec<_>>())
}

fn escaped_ident(name: &str) -> Ident {
    if matches!(name, "crate" | "self" | "super" | "Self") {
        return format_ident!("{name}_");
    }
    syn::parse_str::<Ident>(name)
        .unwrap_or_else(|_| Ident::new_raw(name, proc_macro2::Span::call_site()))
}
